### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gdurelle** [rossta/serviceworker-rails-sandbox#1]
Hi, 

The idea seems great. 
I'm really struggling to add my assets (like application.css & application.css) because of the token added on it on precompilation.

But I have no idea whatsoever of how to use this gem to do what I want and define my service worker to cache and fetch my assets.
I've looked at the sandbox app and the doc several time, but it is still very obscur to me.

Could you provide very simple example ? 
Like only one index page with its rails-way included css+js and the config to see them even though the name is complex (you know: /assets/application.self-1234azerty6789.css)

**Comment by rossta** [comment]
Thanks for the feedback. I would like to add something like that. In the meantime, check out a couple blog posts that may help:

* [Service Worker on Rails](https://rossta.net/blog/service-worker-on-rails.html) - general background
* [Offline Page for your Rails application](https://rossta.net/blog/offline-page-for-your-rails-application.html) - tutorial for using Service Worker to serve an offline error page (may help with the "getting started" part of what you're requesting)

**Comment by gdurelle** [comment]
Thanks for the links started reading.

What about PostMessages to send the proper url to cache to the ServiceWorker ? 
```javascript
addEventListener('message', function(event){...}
```
That would let us retrieve the "tokenized" assets urls on the page parsing the DOM in the JS file that register the ServiceWorker, and then sending them to the ServiceWorker through a message.
(security concerns ? other problems ?)

**Comment by rossta** [comment]
Since [`serviceworker-rails`](https://github.com/rossta/serviceworker-rails) lets you integrate your Service Worker script with the asset pipeline, there's no need to pass around urls in messages (if I understand your suggestion). 

You could interpolate the "tokenized" asset url via the helpers made available to the Sprockets environment. The following shows how you could cache fingerprinted assets during the Service Worker install event.

```javascript
// serviceworker.js

self.addEventListener('install', function onInstall(event) {
  event.waitUntil(
    caches.open('some-cache-key').then(function prefill(cache) {
      return cache.addAll([
        '<%= asset_path "application.js" %>',
        '<%= asset_path "application.css" %>',
      ]);
    })
  );
});
```

**Comment by gdurelle** [comment]
That helped me a lot !!
Works perfectly.

Adding your code snippet to the doc would surely help a lot of other people :)

Thanks.

**Comment by Rupinderwadali** [comment]
Hello Developers,
I am trying to use the serviceworker-rails gem in my rails app. I follow the https://rossta.net/blog/offline-page-for-your-rails-application.html tutorial and create one page that works offline. But what I need to do is to add the views of my apps (like I want to add multiple dynamic web pages to work offline as the main page have the link of all the other web pages to navigate). This app includes images as well as audios. Please suggest me how do I add the views( web pages) of my app to work offline using serviceworker-rails?
Thanks :)

**Comment by rossta** [comment]
Hi @Rupinderwadali, thanks for your comment. There are a lot of general resources out there by now that can help give you some ideas. I recommend checking out the Mozilla [Offline Cookbook](https://serviceworke.rs/) for ideas on how to extend the functionality of your service worker. Some of those strategies I've adopted and added to the [Serviceworker on Rails Sandbox](https://serviceworker-rails.herokuapp.com/) ([source code](https://github.com/rossta/serviceworker-rails-sandbox)). Please check out the source code of these apps to see how it's all implemented. Hope that's helpful.

**Comment by Rupinderwadali** [comment]
Hello @rossta, Thanks for you guidance :). I will try this.

**Comment by Rupinderwadali** [comment]
@rossta 
I just wanted to know that as we created a new page offline.html in the public directory. And i think to offline the whole app we need to use the code of the serviceworker in the application.html.erb file. Is that possible? Or is there any way to add the all view to work offline?
Thank you :)

**Comment by rossta** [comment]
Do you mean add to the `Caches` object? You can add the contents of any request to the cache to be made available to work offline later. Simply use the same technique to add to the cache that as described above:

```
self.addEventListener('install', function onInstall(event) {
  event.waitUntil(
    caches.open('some-cache-key').then(function prefill(cache) {
      return cache.addAll([
        '/page-1',
        '/page-2',
        // etc
      ]);
    })
  );
});
```

To access these cached pages when offline, you'll need to instruct the serviceworker to use the fallback, as described in the my blog post. Hope that's helpful.
