### ISSUE TITLE
iOS?

### ISSUE THREAD

**Issue by gregblass** [rossta/serviceworker-rails-sandbox#3]
Just wondering if these demos are supposed to work in Safari on iOS.

In fact there are no mentions of operating systems at all?

A lot (maybe even most?) Rails developers use Apple stuff...

**Comment by rossta** [comment]
Perhaps a link to [caniuse.com](http://caniuse.com/#feat=serviceworkers) would help? PRs are welcome. 

[Service Worker support](http://caniuse.com/#feat=serviceworkers) has shipped in only a few browsers, including Chrome and Firefox, but neither Safari nor Safari iOS.

**Comment by gregblass** [comment]
I saw that right after I posted this, haha. Then I came back here and it looked like the comment had to be approved or something because it wasn't there. Either that or github was being slow.

Yeah, that sucks that Safari is so behind the ball. It makes sense with Google basically leading the way with development.

Apple wants to keep things in the app store, thats how they make money :(
