### ISSUE TITLE
DATABASE_URL

### ISSUE THREAD

**Issue by valinaga** [rossta/serviceworker-rails-sandbox#7]
Hi,

Trying to run the sample but stuck at database configuration. Pls. let me know a sample DATABASE_URL which will work with the code.
I can create whatever database is needed in postgres.
Thanks,

Vali

UPDATE: Solved!

**Comment by rossta** [comment]
@valinaga Sorry for the late response. I haven't documented the setup for running this app very well yet. Sounds like you got it working?
